name: Debug workflow

on:
  merge_group:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: debug
        run: cat /home/runner/work/_temp/_github_workflow/event.json

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: DeterminateSystems/nix-installer-action@main

      - name: flakehub-cache-action
        uses: DeterminateSystems/flakehub-cache-action@b71095acadea12c85f1aa62bd16aefcad539271b
        with:
          source-pr: 130
